[metadata]
name = mediadex
summary = Index media metadata into multiple backends
description_file =
    README.md
author = Joni Harker
author_email = code@gentlydownthe.net
home_page = https://github.com/ConsoleCatzirl/mediadex-python
classifier =
    Intended Audience :: Developers
    License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12

[bdist_wheel]
universal = 1

[options.entry_points]
console_scripts =
    mediadex = mediadex.cmd:main

[pbr]
skip_authors = true
skip_changelog = true
skip_reno = true
